# Uncomment this line to define a global platform for your project
# platform :ios, '8.1'

xcodeproj 'Cramr v2.0.xcodeproj'

target 'Cramr v2.0' do

pod 'JSQSystemSoundPlayer'

pod 'JSQMessagesViewController'  

end

target 'Cramr v2.0Tests' do

end

